export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const PAGE_CHANGESTATE ='PAGE_CHANGESTATE';

export const HOME_GETINITDATA_ACTION = 'HOME_GETINITDATA_ACTION';
export const HOME_SETINITDATA = 'HOME_SETINITDATA';