export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

//页面状态
export const PAGE_CHANGESTATE = 'PAGE_CHANGESTATE';
export const PAGE_SET_PAGENAME = 'PAGE_SET_PAGENAME';
//首页
export const HOME_GETINITDATA_ACTION = 'HOME_GETINITDATA_ACTION';
export const HOME_SETINITDATA = 'HOME_SETINITDATA';
export const HOME_PAGE_STATE = 'HOME_PAGE_STATE';
//分类页
export const CATERGRY_GETINITDATA_ACTION = 'CATERGRY_GETINITDATA_ACTION';
export const CATERGRY_SETINITDATA = 'CATERGRY_SETINITDATA';
export const CATERGRY_PAGE_STATE = 'CATERGRY_PAGE_STATE';
